spring:
  application:
    name: Backend
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/knowledgebase?useSSL=false&serverTimezone=UTC
    username: root    # TODO: 修改为你的数据库用户名
    password: 123456  # TODO: 修改为你的MYSQL密码
  web:
    error:
      whitelabel:
        enabled: false  # 使用默认错误页面

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.knowledgebase.backend.entity
  configuration:
    map-underscore-to-camel-case: true

# JWT TOKEN
jwt:
  secret: kfc-crazy-thursday-vme-fifty-dhu-dhu
  expiration: 86400000  # 24 hours in ms

# 阿里云OSS
aliyun:
  oss:
    endpoint: http://oss-your-endpoint
    bucket-name: your-bucket-name
    access-key-id: your-access-key-id
    access-key-secret: your-access-key-secret
    folder: knowledge
