spring:
  application:
    name: Backend
  # 数据库相关
  datasource:
    url: jdbc:mysql://localhost:3306/knowledgebase?useSSL=false&serverTimezone=UTC
    username: root    # 启动前请修改为你的数据库用户名和密码
    password: 123456
  web:
    error:
      whitelabel:
        enabled: false # 使用默认的错误页面

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # mapper映射文件位于resources/mapper/*.xml
  type-aliases-package: com.knowledgebase.backend.entity  # 映射的实体类位于 entity/*.java
  configuration:
    map-underscore-to-camel-case: true # 驼峰映射

# JWT 配置
jwt:
  secret: kfc-crazy-thursday-vme-fifty-dhu-dhu
  expiration: 86400000  # 24小时毫秒数